### ISSUE TITLE
Improved error for expand wildcard rule

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#15004]
### Is your feature request related to a problem or challenge?

Found by @mhilton upstream in InfluxDB IOx

Running this query, results in a confusing error message

```sql
create table foo(a int, b int, c timestamp) as values (1,2,'2025-01-01T12:01:02');

SELECT *
FROM foo
WHERE c >= NOW() - INTERVAL '1 hour'
GROUP BY a;
```

```
> SELECT *
FROM foo
WHERE c >= NOW() - INTERVAL '1 hour'
GROUP BY a;
expand_wildcard_rule
caused by
Schema error: No field named foo.b. Valid fields are foo.a.
```

If you explicitly list out the column (`b` instead of `*`) you get a better message:

```
> SELECT b
FROM foo
WHERE c >= NOW() - INTERVAL '1 hour'
GROUP BY a;
Error during planning: Projection references non-aggregate values: Expression foo.b could not be resolved from available columns: foo.a
```

### Describe the solution you'd like

I would like a better error

Perhaps something like

> While expanding wildcard, column "b" must appear in the GROUP BY clause or must be part of an aggregate function.

Bonus points for also improving the message `Error during planning: Projection references non-aggregate values: Expression foo.b could not be resolved from available columns: foo.a`

### Additional context

Here is what DuckDB reports 

```
D SELECT *
  FROM foo
  WHERE c >= NOW() - INTERVAL '1 hour'
  GROUP BY a;
Binder Error:
column "b" must appear in the GROUP BY clause or must be part of an aggregate function.
Either add it to the GROUP BY list, or use "ANY_VALUE(b)" if the exact value of "b" is not important.
```

Here is what postgres says

```sql
postgres=# SELECT *
  FROM foo
  WHERE c >= NOW() - INTERVAL '1 hour'
  GROUP BY a;
ERROR:  column "foo.b" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT *
```

**Comment by alamb** [comment]
I think this is a good first issue as the code will be relatively simple and it will introduce people to the DataFusion dev process

**Comment by Jiashu-Hu** [comment]
take

**Comment by Jiashu-Hu** [comment]
hi @alamb 
I've completed the logic part of this issue, but since this issue is about some error messages that will cause the CI process to fail, should I also modify the related test message?
Thank you very much

**Comment by alamb** [comment]
> hi [@alamb](https://github.com/alamb) I've completed the logic part of this issue, but since this issue is about some error messages that will cause the CI process to fail, should I also modify the related test message? Thank you very much

Yes please!

**Comment by Jiashu-Hu** [comment]
Hi @alamb, seems the file that I'm working on (expand_wildcard_rule.rs) just has been deleted in 16 hours ago by [Remove expand wildcard rule #15170](https://github.com/apache/datafusion/pull/15170), this means refactoring my current code into the new structure will take a bit longer—LOL. I’ll close my existing pull request and submit a new PR once I’ve merged it with the updated logic. Sorry for waiting

**Comment by alamb** [comment]
Thanks for the update @Jiashu-Hu  🙏 

I did verify that the error is still the same on main

```rust
DataFusion CLI v46.0.0
> create table foo(a int, b int, c timestamp) as values (1,2,'2025-01-01T12:01:02');

SELECT *
FROM foo
WHERE c >= NOW() - INTERVAL '1 hour'
GROUP BY a;
0 row(s) fetched.
Elapsed 0.025 seconds.

Error during planning: Projection references non-aggregate values: Expression foo.b could not be resolved from available columns: foo.a
```
