### ISSUE TITLE
Left join not working?

### ISSUE THREAD

**Issue by luobei42** [apache/datafusion#3819]
Just ran into an issue with a left join. The right table's result is missing, but that should work in a left join. Using datafusion==0.6.0 from python. The following is a small test case to reproduce the issue from python:

import pyarrow as pa
import datafusion

ctx = datafusion.SessionContext()

batch = pa.RecordBatch.from_arrays(
    [pa.array(a) for a in [
        [0, 1, 2, 3],
        ['Aldous0 Abfalterer0', 'Bob0 Abramovich0', 'Cyril0 Jobstreibitzer0', 'Dmitry0 Laurent0']]
    ],
    names=['id', 'name']
)
ctx.register_record_batches('author', [[batch]])

batch = pa.RecordBatch.from_arrays(
    [pa.array(a) for a in [
        [0, 1, 2, 3, 4, 5],
        [1, 2, 2, 3, 3, 3],
        ['always a true house', 'always one true banana', 'never the false tree', 'always the true table',
          'never a false house', 'always one green window']]
    ],
    names=['id', 'author_id', 'name']
)
ctx.register_record_batches('book', [[batch]])

print(ctx.sql("select count(*) from author").collect()[0].to_pylist()) #ok
print(ctx.sql("select count(*) from book").collect()[0].to_pylist()) #ok
print(ctx.sql("""\
SELECT a.id, a.name, count(distinct b.id) 
            from author a 
            left join book b on a.id=b.author_id
            where a.id=0
            group by a.id, a.name
""").collect()[0].to_pylist()) #no result, left join not working

**Comment by alamb** [comment]
Hi @luobei42  -- the `bug` label is added when the ticket is created. 

I am not familiar with datafusion python, and I was not able to reproduce your report  with datafusion-cli from master (maybe it was fixed previously 🤔 )


```sql
(arrow_dev) alamb@MacBook-Pro-8:~/Software/arrow-datafusion2$ datafusion-cli
DataFusion CLI v13.0.0
❯ 
create table author
as
select column1 as id, column2 as name from
(VALUES
  (0, 'Aldous0 Abfalterer0')
 ,(1, 'Bob0 Abramovich0')
 ,(2, 'Cyril0 Jobstreibitzer0')
 ,(3, 'Dmitry0 Laurent0')
)as sq;

0 rows in set. Query took 0.002 seconds.
❯ 
create table book
AS
select column1 as id, column2 as author_id, column3 as name
from
(VALUES
 (0,1,'always a true house')
 ,(1,2,'always one true banana')
 ,(2,2,'never the false tree')
 ,(3,3,'always the true table')
 ,(4,3,'never a false house')
 ,(5,3,'always one green window')
) as sq;

0 rows in set. Query took 0.001 seconds.
❯ SELECT a.id, a.name, count(distinct b.id)
from author a
left join book b on a.id=b.author_id
where a.id=0
group by a.id, a.name;
+----+---------------------+----------------------+
| id | name                | COUNT(DISTINCT b.id) |
+----+---------------------+----------------------+
| 0  | Aldous0 Abfalterer0 | 0                    |
+----+---------------------+----------------------+
1 row in set. Query took 0.004 seconds.
❯ 
select count(*) from author;

+-----------------+
| COUNT(UInt8(1)) |
+-----------------+
| 4               |
+-----------------+
1 row in set. Query took 0.000 seconds.
❯ select count(*) from book;

+-----------------+
| COUNT(UInt8(1)) |
+-----------------+
| 6               |
+-----------------+
1 row in set. Query took 0.000 seconds.
```

**Comment by luobei42** [comment]
Hi Andrew,

Thanks for checking. I ran the above test again against the latest version of datafusion-python (using the git repo git@github.com:datafusion-contrib/datafusion-python.git as recommended on https://pypi.org/project/datafusion/0.6.0/). With this version I can still reproduce the problem (left join query yields no results).

Next I tried to do a Rust build of this repo here to reproduce your datafusion-cli run, but "cargo build" failed to create an executable, yet did not issue any errors on the command line (I am no Rust dev, so I could not diagnose further).

My guess at this point is that datafusion itself works, but the python binding has some issue.

**Comment by Dandandan** [comment]
One thing I see is that you use `collect()[0]` (taking the first partition) in your example, but it might return multiple partitions if you have multiple cores. Did you try looking at all of the returned partitions?

**Comment by luobei42** [comment]
Hi Daniël, it seems that I was not aware of this API feature - I just assumed that collect() only returns one result from experiments. 
The correct result is indeed returned in another partition!
Is there an API to combine all the partitions automatically? Something like collect_in_one_partition()?

**Comment by luobei42** [comment]
Btw, the documentation on the pypi page is misleading in this regard (https://pypi.org/project/datafusion/0.6.0/). The code examples's comment says:

```
# execute and collect the first (and only) batch
result = df.collect()[0]
```

**Comment by andygrove** [comment]
The published Python bindings for DataFusion are extremely out-of-date. Could you try with latest from https://github.com/apache/arrow-datafusion-python ?

**Comment by luobei42** [comment]
I tried to use those bindings; running "maturin develop" still works, but "python -m pytest" fails with test errors. Running the above example yields a similar result.

So, I guess the API documentation is just wrong (also in the bindings repo's README) and calling collect()[0] is not the  right API (though generally I am a fan of calling collect, it's so much cheaper).

**Comment by HaoYang670** [comment]
Hi @luobei42 . I tested on the datafusion-python 0.6.0 (installed by pip), but I can't reproduce the bug.
```python
In [1]: import pyarrow as pa

In [2]: import datafusion

In [3]: datafusion.__version__
Out[3]: '0.6.0'

In [4]: batch = pa.RecordBatch.from_arrays(
   ...: [pa.array(a) for a in [
   ...: [0, 1, 2, 3],
   ...: ['Aldous0 Abfalterer0', 'Bob0 Abramovich0', 'Cyril0 Jobstreibitzer0', 'Dmitry0 Laurent0']]
   ...: ],
   ...: names=['id', 'name']
   ...: )

In [5]: batch0 = pa.RecordBatch.from_arrays(
   ...: [pa.array(a) for a in [
   ...: [0, 1, 2, 3, 4, 5],
   ...: [1, 2, 2, 3, 3, 3],
   ...: ['always a true house', 'always one true banana', 'never the false tree', 'always the true table',
   ...: 'never a false house', 'always one green window']]
   ...: ],
   ...: names=['id', 'author_id', 'name']
   ...: )

In [6]: ctx = datafusion.SessionContext()

In [7]: ctx.register_record_batches('author', [[batch]])

In [8]: ctx.register_record_batches('book', [[batch0]])

In [9]: ctx.sql("select count() from author").collect()
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-10-19463c0b77f0> in <module>
----> 1 ctx.sql("select count() from author").collect()

Exception: DataFusion error: Plan("The function Count expects 1 arguments, but 0 were provided")

In [10]: ctx.sql("select count(*) from author").collect()
Out[10]: 
[pyarrow.RecordBatch
 COUNT(UInt8(1)): uint64]

In [11]: ctx.sql("select count(*) from book").collect()
Out[11]: 
[pyarrow.RecordBatch
 COUNT(UInt8(1)): uint64]

In [14]: ctx.sql("""
    ...: SELECT a.id, a.name, count(distinct b.id)
    ...: from author a
    ...: left join book b on a.id=b.author_id
    ...: where a.id=0
    ...: group by a.id, a.name
    ...: """).show
Out[14]: <function DataFrame.show>

In [15]: ctx.sql("""
    ...: SELECT a.id, a.name, count(distinct b.id)
    ...: from author a
    ...: left join book b on a.id=b.author_id
    ...: where a.id=0
    ...: group by a.id, a.name
    ...: """).show()
+----+---------------------+----------------------+
| id | name                | COUNT(DISTINCT b.id) |
+----+---------------------+----------------------+
| 0  | Aldous0 Abfalterer0 | 0                    |
+----+---------------------+----------------------+
```

My code is a little different from yours in that I use `show` instead of `collect`.

**Comment by alamb** [comment]
This seems to be unreproduceable now, so closing it down. Let's reopen another ticket if we find an issue
